server:
  port: 8092
  servlet:
    context-path: /api/v1

spring:
  ### 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置初始化大小/最小/最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 获取连接等待超时时间
    max-wait: 60000
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    # 一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面的SQL无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connection-properties:
      druid:
        stat:
          merge-sql: true
          slow-sql-millis: 5000

  ### jpa配置
  jpa:
    show-sql: true

  ### redis缓存配置
  redis:
    # 默认redis数据库为db0
    database: 0
    # 服务器地址，默认为localhost
    host: localhost
    # 链接端口，默认为6379
    port: 6379
    # redis密码默认为空
    password: 123456
